import assert from 'assert'
import strTruncate from '../src/strTruncate.mjs'


describe(`strTruncate`, function() {

    it(`should return '' when str is not an effective string`, function() {
        assert.strict.deepStrictEqual(strTruncate(null, 10), '')
        assert.strict.deepStrictEqual(strTruncate(undefined, 10), '')
        assert.strict.deepStrictEqual(strTruncate('', 10), '')
        assert.strict.deepStrictEqual(strTruncate(123, 10), '')
        assert.strict.deepStrictEqual(strTruncate(['a'], 10), '')
        assert.strict.deepStrictEqual(strTruncate({ a: 1 }, 10), '')
    })

    it(`should return original string when maxLen is not an effective non-negative integer`, function() {
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', -1), 'abcdefghij')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 1.5), 'abcdefghij')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', null), 'abcdefghij')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', undefined), 'abcdefghij')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 'abc'), 'abcdefghij')
    })

    it(`should return original string without ellipsis when str is shorter than maxLen`, function() {
        assert.strict.deepStrictEqual(strTruncate('abc', 10), 'abc')
    })

    it(`should return original string without ellipsis when str length equals maxLen`, function() {
        assert.strict.deepStrictEqual(strTruncate('abcde', 5), 'abcde')
    })

    it(`should cut and append ellipsis when str is longer than maxLen`, function() {
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3), 'abc...')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 9), 'abcdefghi...')
    })

    it(`should cut to empty and append ellipsis when maxLen is 0`, function() {
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 0), '...')
    })

    it(`should accept numeric string as maxLen`, function() {
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', '3'), 'abc...')
    })

    it(`should count by characters so chinese is not cut into broken bytes`, function() {
        assert.strict.deepStrictEqual(strTruncate('中文測試字串', 2), '中文...')
        assert.strict.deepStrictEqual(strTruncate('中文測試字串', 6), '中文測試字串')
    })

    it(`should append message generated by opt.funWithMsg after ellipsis`, function() {
        let r = strTruncate('abcdefghij', 3, {
            funWithMsg: (str) => `(truncated, total ${str.length} chars)`,
        })
        assert.strict.deepStrictEqual(r, 'abc...(truncated, total 10 chars)')
    })

    it(`should pass original str and maxLen into opt.funWithMsg`, function() {
        let cstr = null
        let cmaxLen = null
        strTruncate('abcdefghij', 3, {
            funWithMsg: (str, maxLen) => {
                cstr = str
                cmaxLen = maxLen
                return ''
            },
        })
        //str須為原始未裁切字串, 故可於訊息內取用原始長度
        assert.strict.deepStrictEqual(cstr, 'abcdefghij')
        assert.strict.deepStrictEqual(cmaxLen, 3)
    })

    it(`should not call opt.funWithMsg when str is not truncated`, function() {
        let called = false
        let r = strTruncate('abc', 10, {
            funWithMsg: () => {
                called = true
                return '(msg)'
            },
        })
        assert.strict.deepStrictEqual(called, false)
        assert.strict.deepStrictEqual(r, 'abc')
    })

    it(`should ignore opt.funWithMsg when it does not return an effective string`, function() {
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3, { funWithMsg: () => null }), 'abc...')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3, { funWithMsg: () => '' }), 'abc...')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3, { funWithMsg: () => 123 }), 'abc...')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3, { funWithMsg: () => ({ a: 1 }) }), 'abc...')
    })

    it(`should ignore opt.funWithMsg when it is not a function`, function() {
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3, { funWithMsg: 'msg' }), 'abc...')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3, { funWithMsg: null }), 'abc...')
    })

    it(`should ignore invalid opt`, function() {
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3, null), 'abc...')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3, 'invalid'), 'abc...')
        assert.strict.deepStrictEqual(strTruncate('abcdefghij', 3), 'abc...')
    })

})
