language: node_js
node_js:
    - "11"
    - "10"
    - "9"
    - "8"
install:
    - npm install
    - npm install -g codecov
script:
    - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
    - codecov