export { default as pmMap } from '../../src/pmMap.mjs'
export { default as ispint } from '../../src/ispint.mjs'
export { default as isfun } from '../../src/isfun.mjs'
export { default as iseobj } from '../../src/iseobj.mjs'
export { default as isearr } from '../../src/isearr.mjs'
export { default as isbol } from '../../src/isbol.mjs'
export { default as cint } from '../../src/cint.mjs'
